import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/navbar-wrapper";
import { UserProvider } from "@/context/UserContext";
import IdleLogout from "@/components/idle-logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <IdleLogout />
          <NavbarWrapper>{children}</NavbarWrapper>
        </UserProvider>

        <footer className="w-full h-15 bg-bg text-white font-bold text-center py-5">
          Direitos autorais © 2025 alliancar. Todos os direitos reservados.
        </footer>
      </body>
    </html>
  );
}
